class Fields:

    # datasets columns

    # generic
    filename = "filename"
    date = "date"
    execution_time = "execution_time"
    relative_days = "relative_days"
    relative_weeks = "relative_weeks"
    day_of_week = "day_of_week"

    # google analytics
    ga_source = "ga_source"
    ga_channel_grouping = "ga_channel_grouping"
    ga_sessions = "ga_sessions"
    ga_users = "ga_users"

    # oracle employees
    ora_location_id = "location_id"
    ora_rev_center_id = "revenue_center_id"
    ora_ora_rev_center_name = "revenue_center_name"
    ora_employee_id = "employee_id"
    ora_employee_first_name = "employee_first_name"
    ora_employee_last_name = "employee_last_name"
    ora_menu_item_id = "menu_item_id"
    ora_menu_item_name = "menu_item_name"
    ora_menu_item_master_name = "menu_item_master_name"
    ora_major_group_name = "major_group_name"
    ora_family_group_name = "family_group_name"
    ora_sales_total = "sales_total"
    ora_sales_count = "sales_count"
    ora_sales_gross_before_discount = "sales_gross_before_discount"
    ora_discount_total = "discount_total"

    # oracle guest
    ora_guest_check_id = "guest_check_id"
    ora_order_type_id = "order_type_id"
    ora_check_open_datetime = "check_open_datetime"
    ora_check_close_datetime = "check_close_datetime"
    ora_num_guests = "num_guests"
    ora_check_total = "check_total"
    ora_void_total = "void_total"
    ora_tip_total = "tip_total"
    ora_error_correct_total = "error_correct_total"
    ora_transfer_status_code = "transfer_status_code"
    ora_transfer_status = "transfer_status"
    ora_transfer_to_check_num = "transfer_to_check_num"
    ora_service_charge = "service_charge"
    ora_check_sub_total = "check_sub_total"
    ora_order_type_name = "order_type_name"
    ora_guest_employee_id = ora_employee_id
    ora_guest_employee_first_name = ora_employee_first_name
    ora_guest_employee_last_name = ora_employee_last_name
    ora_check_duration = "check_duration"
    ora_table_reference = "table_reference"
    ora_check_tot_items = "check_tot_items"
    ora_error_correct_count = "error_correct_count"
    ora_is_employee_meal = "is_employee_meal"
    productivity = "productivity"
    hours_per_week = "hours_per_week"

    missing = "_missing_"

    relative_cycle_28 = "relative_cycle_28"
    relative_cycle_7 = "relative_cycle_7"

    fcst_observation = "data_point_class"

    period_of_day = "period_of_day"
    shift_id = "shift_id"

    # severooms
    venue_name = "venue_name"
    shift_name = "shift_name"
    created_date = "created_date"
    created_time = "created_time"
    reservation_date = "reservation_date"
    reservation_time = "reservation_time"
    update_date = "update_date"
    update_time = "update_time"
    full_name = "full_name"
    reservation_status = "reservation_status"
    detailed_status = "detailed_status"
    confirmation_id = "confirmation_id"
    booked_by = "booked_by"
    reservation_notes = "reservation_notes"
    booked_covers = "booked_covers"
    reservation_tag = "reservation_tag"
    phone_number = "phone_number"
    guest_email = "guest_email"
    birthday = "birthday"
    client_notes = "client_notes"
    anniversary = "anniversary"
    company = "company"
    job_title = "job_title"
    loyalty_id = "loyalty_id"
    loyalty_rank = "loyalty_rank"
    loyalty_tier = "loyalty_tier"
    mkt_opt_in = "mkt_opt_in"
    guest_total_spend = "guest_total_spend"
    prepayment_net_usd = "prepayment_net_usd"
    prepayment_tax_usd = "prepayment_tax_usd"
    prepayment_service_charge_usd = "prepayment_service_charge_usd"
    prepayment_gratuity_usd = "prepayment_gratuity_usd"
    prepayment_gross_usd = "prepayment_gross_usd"
    prepayment_net = "prepayment_net"
    prepayment_tax = "prepayment_tax"
    prepayment_service_charge = "prepayment_service_charge"
    prepayment_gratuity = "prepayment_gratuity"
    prepayment_total = "prepayment_total"
    prepayment_onsite_gross_usd = "prepayment_onsite_gross_usd"
    prepayment_onsite_net_usd = "prepayment_onsite_net_usd"
    menu_item_cost = "menu_item_cost"
    margin = "margin"
    total_cost = "total_cost"

    # discounts
    ora_discount_daily_total_id = "discount_daily_total_id"
    ora_revenue_center_id = "revenue_center_id"
    ora_discount_id = "discount_id"
    ora_discount_count = "discount_count"
    ora_discount_gross_vat = "discount_gross_vat"
    ora_discount_num = "discount_num"
    ora_discount_name = "discount_name"
    ora_discount_master_num = "discount_master_num"
    ora_discount_master_name = "discount_master_name"
    ora_revenue_center_num = "revenue_center_num"
    ora_revenue_center_name = "revenue_center_name"
    ora_revenue_center_master_num = "revenue_center_master_num"
    ora_revenue_center_master_name = "revenue_center_master_name"
    ora_location_ref = "location_ref"
    ora_location_name = "location_name"


class Storage:

    # container names
    staging = "staging"
    bronze = "bronze"
    silver = "silver"
    account_name = "gruppotavolastorage"

    # filepaths
    bronze_ga = "googleanalytics/googleanalytics.parquet"
    bronze_oracle_employees = "oracle/employees.parquet"
    bronze_oracle_guests = "oracle/guests.parquet"
    bronze_oracle_discounts = "oracle/discounts.parquet"
    silver_dates = "dates/dates.parquet"
    silver_employees = "employees/employees.parquet"
    silver_items = "items/items.parquet"
    silver_discounts = "discounts/discounts.parquet"
    bronze_forecast = "forecast/forecast.parquet"
    employee_hours = "external_uploads/employees_hours.xlsx"
    item_cost = "external_uploads/item_cost.xlsx"
    future_reservations = "sevenrooms/future/"
    yesterday_reservations = "sevenrooms/yesterday/"
    bronze_yesterday_reservations = "sevenrooms/yesterday.parquet"
    bronze_future_reservations = "sevenrooms/future.parquet"
